apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: talend-registry
  containers:
    - name: talend-tsbi-dev
      image: artifactory.datapwn.com/tlnd-docker-prod/talend/common/tsbi/jdk8-dev-base:2.9.32-20220426164643
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1"
